### ISSUE TITLE
CUDA 9 compile fails

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/alpaka#426]
It is not possible to compile an alpaka example with CUDA9.

e.g. hello world

```
[ 70%] Linking CXX executable helloWorld
/sw/global/compilers/gcc/6.3.0/include/c++/6.3.0/tuple: In instantiation of ‘static constexpr bool std::_TC<<anonymous>, _Elements>::_MoveConstructibleTuple() [with _UElements = {std::tuple<std::_Placeholder<1>, std::reference_wrapper<unsigned int* const>, std::reference_wrapper<const alpaka::vec::Vec<std::integral_constant<long unsigned int, 3ul>, long unsigned int> > >}; bool <anonymous> = true; _Elements = {std::_Placeholder<1>, std::reference_wrapper<unsigned int* const>, std::reference_wrapper<const alpaka::vec::Vec<std::integral_constant<long unsigned int, 3ul>, long unsigned int> >}]’:
/sw/global/compilers/gcc/6.3.0/include/c++/6.3.0/tuple:626:248:   required by substitution of ‘template<class ... _UElements, typename std::enable_if<(((std::_TC<(sizeof... (_UElements) == 1), std::_Placeholder<1>, std::reference_wrapper<unsigned int* const>, std::reference_wrapper<const alpaka::vec::Vec<std::integral_constant<long unsigned int, 3ul>, long unsigned int> > >::_NotSameTuple<_UElements ...>() && std::_TC<(1ul == sizeof... (_UElements)), std::_Placeholder<1>, std::reference_wrapper<unsigned int* const>, std::reference_wrapper<const alpaka::vec::Vec<std::integral_constant<long unsigned int, 3ul>, long unsigned int> > >::_MoveConstructibleTuple<_UElements ...>()) && std::_TC<(1ul == sizeof... (_UElements)), std::_Placeholder<1>, std::reference_wrapper<unsigned int* const>, std::reference_wrapper<const alpaka::vec::Vec<std::integral_constant<long unsigned int, 3ul>, long unsigned int> > >::_ImplicitlyMoveConvertibleTuple<_UElements ...>()) && (3ul >= 1)), bool>::type <anonymous> > constexpr std::tuple< <template-parameter-1-1> >::tuple(_UElements&& ...) [with _UElements = {std::tuple<std::_Placeholder<1>, std::reference_wrapper<unsigned int* const>, std::reference_wrapper<const alpaka::vec::Vec<std::integral_constant<long unsigned int, 3ul>, long unsigned int> > >}; typename std::enable_if<(((std::_TC<(sizeof... (_UElements) == 1), std::_Placeholder<1>, std::reference_wrapper<unsigned int* const>, std::reference_wrapper<const alpaka::vec::Vec<std::integral_constant<long unsigned int, 3ul>, long unsigned int> > >::_NotSameTuple<_UElements ...>() && std::_TC<(1ul == sizeof... (_UElements)), std::_Placeholder<1>, std::reference_wrapper<unsigned int* const>, std::reference_wrapper<const alpaka::vec::Vec<std::integral_constant<long unsigned int, 3ul>, long unsigned int> > >::_MoveConstructibleTuple<_UElements ...>()) && std::_TC<(1ul == sizeof... (_UElements)), std::_Placeholder<1>, std::reference_wrapper<unsigned int* const>, std::reference_wrapper<const alpaka::vec::Vec<std::integral_constant<long unsigned int, 3ul>, long unsigned int> > >::_ImplicitlyMoveConvertibleTuple<_UElements ...>()) && (3ul >= 1)), bool>::type <anonymous> = <missing>]’
/sw/global/compilers/gcc/6.3.0/include/c++/6.3.0/functional:979:136:   required from ‘std::_Bind<_Functor(_Bound_args ...)>::_Bind(std::_Bind<_Functor(_Bound_args ...)>&&) [with _Functor = std::reference_wrapper<const TestBufferKernel>; _Bound_args = {std::_Placeholder<1>, std::reference_wrapper<unsigned int* const>, std::reference_wrapper<const alpaka::vec::Vec<std::integral_constant<long unsigned int, 3ul>, long unsigned int> >}]’
/home/widera/src/alpaka/include/alpaka/exec/ExecCpuSerial.hpp:151:1:   required from ‘alpaka::exec::ExecCpuSerial<TDim, TSize, TKernelFnObj, TArgs>::operator()() const::<lambda(const TArgs& ...)> [with TDim = std::integral_constant<long unsigned int, 3ul>; TSize = long unsigned int; TKernelFnObj = TestBufferKernel; TArgs = {unsigned int*, alpaka::vec::Vec<std::integral_constant<long unsigned int, 3ul>, long unsigned int>}]’
/home/widera/src/alpaka/include/alpaka/exec/ExecCpuSerial.hpp:142:52:   required from ‘struct alpaka::exec::ExecCpuSerial<TDim, TSize, TKernelFnObj, TArgs>::operator()() const [with TDim = std::integral_constant<long unsigned int, 3ul>; TSize = long unsigned int; TKernelFnObj = TestBufferKernel; TArgs = {unsigned int*, alpaka::vec::Vec<std::integral_constant<long unsigned int, 3ul>, long unsigned int>}]::<lambda(unsigned int* const&, const class alpaka::vec::Vec<std::integral_constant<long unsigned int, 3ul>, long unsigned int>&)>’
/home/widera/src/alpaka/include/alpaka/exec/ExecCpuSerial.hpp:142:50:   required from ‘void alpaka::exec::ExecCpuSerial<TDim, TSize, TKernelFnObj, TArgs>::operator()() const [with TDim = std::integral_constant<long unsigned int, 3ul>; TSize = long unsigned int; TKernelFnObj = TestBufferKernel; TArgs = {unsigned int*, alpaka::vec::Vec<std::integral_constant<long unsigned int, 3ul>, long unsigned int>}]’
/home/widera/src/alpaka/include/alpaka/stream/StreamCpuSync.hpp:214:5:   required from ‘static void alpaka::stream::traits::Enqueue<alpaka::stream::StreamCpuSync, TTask, void>::enqueue(alpaka::stream::StreamCpuSync&, const TTask&) [with TTask = alpaka::exec::ExecCpuSerial<std::integral_constant<long unsigned int, 3ul>, long unsigned int, TestBufferKernel, unsigned int*, alpaka::vec::Vec<std::integral_constant<long unsigned int, 3ul>, long unsigned int> >]’
/home/widera/src/alpaka/include/alpaka/stream/Traits.hpp:76:72:   required from ‘void alpaka::stream::enqueue(TStream&, TTask&&) [with TStream = alpaka::stream::StreamCpuSync; TTask = const alpaka::exec::ExecCpuSerial<std::integral_constant<long unsigned int, 3ul>, long unsigned int, TestBufferKernel, unsigned int*, alpaka::vec::Vec<std::integral_constant<long unsigned int, 3ul>, long unsigned int> >&]’
/home/widera/src/alpaka/example/bufferCopy/src//bufferCopy.cpp:341:38:   required from here
/sw/global/compilers/gcc/6.3.0/include/c++/6.3.0/tuple:483:67: error: mismatched argument pack lengths while expanding ‘std::is_constructible<_Elements, _UElements&&>’
       return __and_<is_constructible<_Elements, _UElements&&>...>::value;
                                                                   ^~~~~
/sw/global/compilers/gcc/6.3.0/include/c++/6.3.0/tuple:484:1: error: body of constexpr function ‘static constexpr bool std::_TC<<anonymous>, _Elements>::_MoveConstructibleTuple() [with _UElements = {std::tuple<std::_Placeholder<1>, std::reference_wrapper<unsigned int* const>, std::reference_wrapper<const alpaka::vec::Vec<std::integral_constant<long unsigned int, 3ul>, long unsigned int> > >}; bool <anonymous> = true; _Elements = {std::_Placeholder<1>, std::reference_wrapper<unsigned int* const>, std::reference_wrapper<const alpaka::vec::Vec<std::integral_constant<long unsigned int, 3ul>, long unsigned int> >}]’ not a return-statement
     }
 ^
```

Software used:
- gcc 6.30
- boost 1.65.1
- cmake 3.9.0
- cuda 9.0.176

@BenjaminW3 It looks like it is something with the `meta::apply` command. Could you see anything which possible triggered the error?

**Comment by psychocoderHPC** [comment]
gcc 6.X is compiling C++ 14 by default. It looks like CUDA9 has problems with C++14.

It looks like it helps to use c++11 by setting `export CXX_FLAGS="-std=c++11"`.
I will check if this solves the issue fully.

**Comment by psychocoderHPC** [comment]
If I switch to `gcc/5.3.0` the issue is gone. It looks like it is something with gcc/6.3.0 and CUDA 9.

**Comment by BenjaminW3** [comment]
This was already part of the original CUDA 9.0 Pull Request description #384. The combination of CUDA and gcc 6 is not enabled in the supprted compiler matrix.

**Comment by psychocoderHPC** [comment]
With gcc 4.9 and CUDA 8 there is the same issue (e.g. in #416)
The compiler only crash if `-DCMAKE_BUILD_TYPE=Debug` is set (like in the CI tests).
I will deeper look to it to get #416 passing the CI.

**Comment by psychocoderHPC** [comment]
The problem is the compiler flag `-G` for the cuda compiler, this will disable all optimizations. Maybe `-G` also increase the compile time of all tests.

**Comment by psychocoderHPC** [comment]
I found the trigger for this issue in #427, but fixing the wrong used stream not solve this issue.

**Comment by psychocoderHPC** [comment]
@BenjaminW3  I removed three posts because i thought the are equal to this issue, but realized the differ, therefore I opened #427

**Comment by BenjaminW3** [comment]
The bug is still triggered when using CUDA 9.1

**Comment by BenjaminW3** [comment]
This should be the same error: https://devtalk.nvidia.com/default/topic/1028112/cuda-setup-and-installation/nvcc-bug-related-to-gcc-6-lt-tuple-gt-header-/post/5234434/#5234434

**Comment by ax3l** [comment]
Not sure if it's silently patched in one of the three CUDA 9.1.X patch releases: https://gist.github.com/ax3l/9489132

**Comment by robertmaynard** [comment]
I can confirm that V9.1.85 + gcc 6.X still has problems with std::tuple.

**Comment by ax3l** [comment]
Thanks for the info Robert! Do you work-around it somehow in your projects?

**Comment by robertmaynard** [comment]
Just ran into the problem and was able to roll back to gcc-5 to work around the problem. Haven't investigated any local workarounds.

**Comment by ax3l** [comment]
Just as a note: NVCC 9.2 fixed the GCC 6 `std::tuple` issues: https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html

```
2.2. CUDA Tools
2.2.1. CUDA Compilers

    The following compilers are supported as host compilers in nvcc
        Clang 5.0
        GCC 7.x
        Microsoft Visual Studio 2017 (RTW and Update 6)
        PGI pgc++ 18.x
        XLC 13.1.6
    __device__ / __constant__ variables are now allowed to have an rvalue reference type.
    Functions in math_functions.hpp have been changed to use memcpy for type punning.

    Added support for std::tuple.
[...]
```

**Comment by robertmaynard** [comment]
Awesome news, I will have to try out CUDA 9.2 and see if my host side `std::tuple` woes with GCC 7 are now gone. 

Since we don't have a hard dependency on Thrust/CUDA we went with forking taotuple for VTK-m ( https://gitlab.kitware.com/third-party/taotuple / https://github.com/taocpp/tuple).

**Comment by ax3l** [comment]
Cool, thanks for the heads up!

The reason why I though about trust was: it's a nvcc only issue and nvcc is shipped with a matching thrust (if CUDA is used as a backend; CUDA is optional for us as well).

**Comment by tdd11235813** [comment]
I hope I can report my current incompatibilities with CUDA9 here as well. At the moment I use the modules on ZIH/Taurus cluster. Trying to compile `examples/bufferCopy` from current develop. At the moment there is only CUDA 8.0.61 working with GCC 5.3.0 and Boost 1.64.0.
CUDA 9.x requires at least Boost 1.65.1. I still need to build & try Boost with gcc 5.4 as it is missing on Taurus.

|CUDA 9.2.88|Boost >=1.65.1|
|---|---|
|gcc 5.4|:question:|
|gcc 5.5|:x:|
|gcc 6.x|:x:|
|gcc 7.x|:x:|

### GCC 7.1 + Boost 1.65.1 + CUDA 9.2.88

```
Currently Loaded Modules:
  1) modenv/classic (S)   2) cmake/3.10.1   3) git/2.15.1   4) gcc/7.1.0   5) bullxmpi/1.2.8.4   6) boost/1.65.1-gnu7.1   7) cuda/9.2.88
```
```bash
# alpaka/example/bufferCopy/build_cuda
cmake .. && make
```
Fails with:

```bash
[ 50%] Building NVCC (Device) object CMakeFiles/bufferCopy.dir/src/bufferCopy_generated_bufferCopy.cpp.o
/sw/taurus/libraries/cuda/9.2.88/bin/nvcc /alpaka/example/bufferCopy/src//bufferCopy.cpp -x=cu -c -o /alpaka/example/bufferCopy/build_cuda/CMakeFiles/bufferCopy.dir/src/./bufferCopy_generated_bufferCopy.cpp.o -ccbin /sw/global/compilers/gcc/7.1.0/bin/g++ -m64 -DALPAKA_ACC_CPU_B_SEQ_T_SEQ_ENABLED -DALPAKA_ACC_CPU_B_SEQ_T_THREADS_ENABLED -DALPAKA_ACC_CPU_B_SEQ_T_FIBERS_ENABLED -DALPAKA_ACC_CPU_B_OMP2_T_SEQ_ENABLED -DALPAKA_ACC_CPU_B_SEQ_T_OMP2_ENABLED -DALPAKA_ACC_GPU_CUDA_ENABLED -DALPAKA_DEBUG=0 -Xcompiler ,\"-fopenmp\",\"-g\" --expt-extended-lambda --expt-relaxed-constexpr --generate-code arch=compute_30,code=sm_30 --generate-code arch=compute_30,code=compute_30 -std=c++11 --use_fast_math --ftz=false -DNVCC -I/sw/taurus/libraries/cuda/9.2.88/include -I/sw/taurus/libraries/boost/1.65.1-gnu7.1/include -I/alpaka/include
/alpaka/include/alpaka/core/Assert.hpp(102): error: this pragma must immediately precede a declaration
```

Same error occurs for `GCC 5.5 + Boost 1.65.1 + CUDA 9.2.88` and `GCC 7.1 + Boost 1.66.0 + CUDA 9.2.88`.
This is setup working, but it is only for CUDA 8.
```
1) modenv/classic (S)   2) gcc/5.3.0   3) bullxmpi/1.2.8.4   4) boost/1.64.0-gnu5.3   5) git/2.15.1   6) cmake/3.10.1   7) cuda/8.0.61
```

**Comment by BenjaminW3** [comment]
Thank you @tdd11235813 for this report. I have tried out CUDA 9.2 in a branch in CI yesterday as well and triggered the same error.
I had not yet time to investigate this deeper and any help would be appreciated!
This seems to be a newly introduced CUDA 9.2 issue.

**Comment by ax3l** [comment]
Jumper over the last two posts and for reference, we need to include this in Alpaka as well: https://github.com/ComputationalRadiationPhysics/picongpu/pull/2628

**Comment by BenjaminW3** [comment]
@ax3l I will try to add those supported combination checks today.

**Comment by ax3l** [comment]
@tdd11235813 do you mind opening an new issue for the CUDA 9.2 report?
This here is quite CUDA 9.0-9.1 specific so far.

**Comment by BenjaminW3** [comment]
I will close this ticket now because:
* there is nothing we can do about it
* there are already newer CUDA versions which support gcc 6 and even gcc 7
* we added diagnostics in the CMake scripts and print a description why this is unsupported

**Comment by ax3l** [comment]
Agreed, we also documented that CUDA 9.0-9.1 actually just works well with GCC <= 5.5.
[Here](https://gist.github.com/ax3l/9489132) and in all our install instructions, e.g. [here](https://github.com/ComputationalRadiationPhysics/picongpu/blob/0.4.2/INSTALL.rst#gcc), and build recipes.
